import type { Metadata } from "next";


export const metadata: Metadata = {
	title: "Siegfried Bozza's portfolio",
	description: "Generated by create next app",
};

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div
			className="
        relative 
				flex flex-col items-center justify-center 
				text-center 
        pt-32 pb-16 px-6 overflow-hidden
        min-h-svh
				gap-8
      "
		>
			{/* Light glow */}
			<div className="absolute left-0 right-0 -top-32 bottom-0 h-224  pointer-events-none opacity-40 bg-[radial-gradient(ellipse_at_center,#1f398e,transparent_60%)]" />

			<span className="text-accent-blue font-bold">Projects</span>

			{children}
    </div>
	)
}
